name: Code Scanning with CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily

permissions:
  security-events: write
  contents: read

jobs:
  codeql-scan:
    name: Run CodeQL Analysis (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      ## 🔹 Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the required Python version

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      ## 🔹 Initialize CodeQL for Python
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      ## 🔹 Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      ## 🔹 Upload CodeQL Results to GitHub Security Tab
      - name: Upload CodeQL Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '../results/python.sarif'  # Adjust if necessary
          category: "python-codeql-scan"  # ✅ Fix: Unique category to prevent conflicts
