name: GitHub Advanced Security Scans

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily

permissions:
  security-events: write
  contents: read
  issues: write  # Required for issue creation

jobs:
  security-scan:
    name: Run Security Scans & Create Issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Step 1: Initialize GitHub CodeQL
      - name: Initialize GitHub CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, python, java  # Change based on your project
          

      # ✅ Step 2: Perform Code Scanning
      - name: Run GitHub Code Scanning (CodeQL)
        uses: github/codeql-action/analyze@v3
        with:
          output: results
          upload: always
          cleanup-level: brutal
          add-snippets: false
          skip-queries: false
          upload-database: true
          wait-for-processing: true
          token: ${{ secrets.GH_PAT }}

      # 🔹 Step 3: Fetch Dependabot Alerts & Create Issues
      - name: Fetch Dependabot Alerts & Create Issues
        run: |
          DEPENDABOT_ALERTS=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts")

          echo "$DEPENDABOT_ALERTS" | jq .

          echo "$DEPENDABOT_ALERTS" | jq -c '.[]' | while IFS= read -r alert; do
            PACKAGE_NAME=$(echo "$alert" | jq -r '.dependency.package.name')
            SEVERITY=$(echo "$alert" | jq -r '.security_vulnerability.severity')
            ALERT_URL=$(echo "$alert" | jq -r '.html_url')

            if [[ -n "$PACKAGE_NAME" && -n "$SEVERITY" && -n "$ALERT_URL" ]]; then
              curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -d "{\"title\":\"[Dependabot] Security Issue: $PACKAGE_NAME ($SEVERITY)\", \"body\":\"[View Alert]($ALERT_URL)\", \"labels\":[\"security\", \"dependabot\"]}" \
                "https://api.github.com/repos/${{ github.repository }}/issues"
            fi
          done

      # 🔹 Step 4: Fetch Secret Scanning Alerts & Create Issues
      - name: Fetch Secret Scanning Alerts & Create Issues
        run: |
          SECRET_ALERTS=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/secret-scanning/alerts")

          echo "$SECRET_ALERTS" | jq .

          echo "$SECRET_ALERTS" | jq -c '.[]' | while IFS= read -r alert; do
            SECRET_TYPE=$(echo "$alert" | jq -r '.secret_type')
            ALERT_URL=$(echo "$alert" | jq -r '.html_url')

            if [[ -n "$SECRET_TYPE" && -n "$ALERT_URL" ]]; then
              curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -d "{\"title\":\"[Secret Scanning] Exposed Secret: $SECRET_TYPE\", \"body\":\"[View Alert]($ALERT_URL)\", \"labels\":[\"security\", \"secret-scanning\"]}" \
                "https://api.github.com/repos/${{ github.repository }}/issues"
            fi
          done
