name: Code Scanning with CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily

permissions:
  security-events: write
  contents: read

jobs:
  codeql-scan:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      ## 🔹 Set up Java (Only if your project includes Java)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java Project (if applicable)
        run: mvn clean install -DskipTests || echo "Build failed, skipping tests"
        continue-on-error: true

      ## 🔹 Initialize CodeQL for Code Scanning
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java, python  # Adjust for your repository's languages

      ## 🔹 Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      ## 🔹 Upload CodeQL Results to GitHub Security Tab
      - name: Upload CodeQL Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '../results/java.sarif'  # Adjust if multiple languages
